/* eslint-disable arrow-body-style */
import { SplitView } from "components/splitView";
import { CodeMirrorPanel } from "features/codemirror";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SplitView>
        <CodeMirrorPanel />
        <div />
      </SplitView>
    </>
  );
};

export default Home;
